DROP TABLE IF EXISTS users CASCADE ;
DROP TABLE IF EXISTS friend_list CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS MPA_films CASCADE;
DROP TABLE IF EXISTS MPA CASCADE;
DROP TABLE IF EXISTS genre_film CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS likes_film_list CASCADE;



CREATE TABLE users (
                       id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email varchar NOT NULL,
                       login varchar NOT NULL,
                       name varchar,
                       birthday date
);

CREATE TABLE friend_list (
                             user_id long NOT NULL,
                             friend_id long,
                             isAcceptRequest boolean,
                             PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE films (
                       id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar,
                       description varchar,
                       releaseDate date,
                       duration int
);

CREATE TABLE MPA_films (
                           film_id long NOT NULL,
                           MPA_id int,
                           PRIMARY KEY (film_id, MPA_id)
);

CREATE TABLE MPA (
                     MPA_id int PRIMARY KEY,
                     MPA_name varchar
);

CREATE TABLE genre_film (
                            film_id long,
                            genre_id int,
                            PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE genre (
                       genre_id int PRIMARY KEY,
                       genre_name varchar
);

CREATE TABLE likes_film_list (
                                 film_id long,
                                 user_like_id long,
                                 PRIMARY KEY (film_id, user_like_id)
);

ALTER TABLE friend_list ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE friend_list ADD FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE MPA_films ADD FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE;

ALTER TABLE MPA_films ADD FOREIGN KEY (MPA_id) REFERENCES MPA (MPA_id) ON DELETE CASCADE;

ALTER TABLE genre_film ADD FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE;

ALTER TABLE genre_film ADD FOREIGN KEY (genre_id) REFERENCES genre (genre_id) ON DELETE CASCADE;

ALTER TABLE likes_film_list ADD FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE;

ALTER TABLE likes_film_list ADD FOREIGN KEY (user_like_id) REFERENCES users (id) ON DELETE CASCADE;

INSERT INTO MPA VALUES (1,'G'), (2,'PG'), (3,'PG-13'), (4,'R'), (5,'NC-17');

INSERT INTO genre VALUES (1,'Комедия'),(2,'Драма'),(3,'Мультфильм'),
                         (4,'Триллер'),(5,'Документальный'),(6,'Боевик');




